# coding: utf-8

"""
    ReportingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.reporting.ad_group_report_scope import AdGroupReportScope
from openapi_client.models.reporting.campaign_report_scope import CampaignReportScope
from typing_extensions import Self

class AccountThroughAdGroupReportScope(BaseModel):
    """
    AccountThroughAdGroupReportScope
    """ # noqa: E501
    account_ids: Optional[List[StrictStr]] = Field(default=None, alias="AccountIds")
    campaigns: Optional[List[Optional[CampaignReportScope]]] = Field(default=None, alias="Campaigns")
    ad_groups: Optional[List[Optional[AdGroupReportScope]]] = Field(default=None, alias="AdGroups")
    __properties: ClassVar[List[str]] = ["AccountIds", "Campaigns", "AdGroups"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in campaigns (list)
        _items = []
        if self.campaigns:
            for _item_campaigns in self.campaigns:
                if _item_campaigns:
                    _items.append(_item_campaigns.to_dict())
            _dict['Campaigns'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ad_groups (list)
        _items = []
        if self.ad_groups:
            for _item_ad_groups in self.ad_groups:
                if _item_ad_groups:
                    _items.append(_item_ad_groups.to_dict())
            _dict['AdGroups'] = _items
        # set to None if account_ids (nullable) is None
        # and model_fields_set contains the field
        if self.account_ids is None and "account_ids" in self.model_fields_set:
            _dict['AccountIds'] = None

        # set to None if campaigns (nullable) is None
        # and model_fields_set contains the field
        if self.campaigns is None and "campaigns" in self.model_fields_set:
            _dict['Campaigns'] = None

        # set to None if ad_groups (nullable) is None
        # and model_fields_set contains the field
        if self.ad_groups is None and "ad_groups" in self.model_fields_set:
            _dict['AdGroups'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountThroughAdGroupReportScope from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AccountIds": obj.get("AccountIds"),
                        "Campaigns": [CampaignReportScope.from_dict(_item) for _item in obj["Campaigns"]] if obj.get("Campaigns") is not None else None,
                        "AdGroups": [AdGroupReportScope.from_dict(_item) for _item in obj["AdGroups"]] if obj.get("AdGroups") is not None else None
        })
        return _obj
