# coding: utf-8

"""
    ReportingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self

class DSASearchQueryPerformanceReportColumn(str, Enum):
    TIMEPERIOD = 'TimePeriod'

    ACCOUNTID = 'AccountId'

    ACCOUNTNAME = 'AccountName'

    ACCOUNTNUMBER = 'AccountNumber'

    ACCOUNTSTATUS = 'AccountStatus'

    CAMPAIGNID = 'CampaignId'

    CAMPAIGNNAME = 'CampaignName'

    CAMPAIGNSTATUS = 'CampaignStatus'

    ADGROUPID = 'AdGroupId'

    ADGROUPNAME = 'AdGroupName'

    ADGROUPSTATUS = 'AdGroupStatus'

    ADID = 'AdId'

    ADSTATUS = 'AdStatus'

    SEARCHQUERY = 'SearchQuery'

    HEADLINE = 'Headline'

    CATEGORYLIST = 'CategoryList'

    LANDINGPAGETITLE = 'LandingPageTitle'

    FINALURL = 'FinalUrl'

    DYNAMICADTARGET = 'DynamicAdTarget'

    DYNAMICADTARGETID = 'DynamicAdTargetId'

    ADDISTRIBUTION = 'AdDistribution'

    LANGUAGE = 'Language'

    NETWORK = 'Network'

    TOPVSOTHER = 'TopVsOther'

    DEVICETYPE = 'DeviceType'

    DEVICEOS = 'DeviceOS'

    IMPRESSIONS = 'Impressions'

    CLICKS = 'Clicks'

    CTR = 'Ctr'

    AVERAGECPC = 'AverageCpc'

    SPEND = 'Spend'

    AVERAGEPOSITION = 'AveragePosition'

    CONVERSIONS = 'Conversions'

    CONVERSIONRATE = 'ConversionRate'

    COSTPERCONVERSION = 'CostPerConversion'

    ASSISTS = 'Assists'

    REVENUE = 'Revenue'

    RETURNONADSPEND = 'ReturnOnAdSpend'

    COSTPERASSIST = 'CostPerAssist'

    REVENUEPERCONVERSION = 'RevenuePerConversion'

    REVENUEPERASSIST = 'RevenuePerAssist'

    CUSTOMERID = 'CustomerId'

    CUSTOMERNAME = 'CustomerName'

    FEEDURL = 'FeedUrl'

    ALLCONVERSIONS = 'AllConversions'

    ALLREVENUE = 'AllRevenue'

    ALLCONVERSIONRATE = 'AllConversionRate'

    ALLCOSTPERCONVERSION = 'AllCostPerConversion'

    ALLRETURNONADSPEND = 'AllReturnOnAdSpend'

    ALLREVENUEPERCONVERSION = 'AllRevenuePerConversion'

    GOAL = 'Goal'

    GOALTYPE = 'GoalType'

    ABSOLUTETOPIMPRESSIONRATEPERCENT = 'AbsoluteTopImpressionRatePercent'

    TOPIMPRESSIONRATEPERCENT = 'TopImpressionRatePercent'

    AVERAGECPM = 'AverageCpm'

    CONVERSIONSQUALIFIED = 'ConversionsQualified'

    ALLCONVERSIONSQUALIFIED = 'AllConversionsQualified'

    DESCRIPTION = 'Description'

	
    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DSASearchQueryPerformanceReportColumn from a JSON string"""
        return cls(json.loads(json_str))


