# coding: utf-8

"""
    ReportingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self

class MMMPerformanceReportColumn(str, Enum):
    TIMEPERIOD = 'TimePeriod'

    CAMPAIGNID = 'CampaignId'

    CAMPAIGNNAME = 'CampaignName'

    ADGROUPID = 'AdGroupId'

    ADGROUPNAME = 'AdGroupName'

    ASSETGROUPID = 'AssetGroupId'

    ASSETGROUPNAME = 'AssetGroupName'

    ACCOUNTID = 'AccountId'

    ACCOUNTNAME = 'AccountName'

    ACCOUNTNUMBER = 'AccountNumber'

    COUNTRY = 'Country'

    STATE = 'State'

    IMPRESSIONS = 'Impressions'

    CLICKS = 'Clicks'

    SPEND = 'Spend'

    CONVERSIONSQUALIFIED = 'ConversionsQualified'

	
    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MMMPerformanceReportColumn from a JSON string"""
        return cls(json.loads(json_str))


