# coding: utf-8

"""
    BulkService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.bulk.operation_error import OperationError
from typing_extensions import Self

class UploadEntityRecordsResponse(BaseModel):
    """
    UploadEntityRecordsResponse
    """ # noqa: E501
    entity_records: Optional[List[StrictStr]] = Field(default=None, alias="EntityRecords")
    request_id: Optional[StrictStr] = Field(default=None, alias="RequestId")
    request_status: Optional[StrictStr] = Field(default=None, alias="RequestStatus")
    errors: Optional[List[Optional[OperationError]]] = Field(default=None, alias="Errors")
    __properties: ClassVar[List[str]] = ["EntityRecords", "RequestId", "RequestStatus", "Errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['Errors'] = _items
        # set to None if entity_records (nullable) is None
        # and model_fields_set contains the field
        if self.entity_records is None and "entity_records" in self.model_fields_set:
            _dict['EntityRecords'] = None

        # set to None if request_id (nullable) is None
        # and model_fields_set contains the field
        if self.request_id is None and "request_id" in self.model_fields_set:
            _dict['RequestId'] = None

        # set to None if request_status (nullable) is None
        # and model_fields_set contains the field
        if self.request_status is None and "request_status" in self.model_fields_set:
            _dict['RequestStatus'] = None

        # set to None if errors (nullable) is None
        # and model_fields_set contains the field
        if self.errors is None and "errors" in self.model_fields_set:
            _dict['Errors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UploadEntityRecordsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "EntityRecords": obj.get("EntityRecords"),
                        "RequestId": obj.get("RequestId") if obj.get("RequestId") is not None else None,
                        "RequestStatus": obj.get("RequestStatus") if obj.get("RequestStatus") is not None else None,
                        "Errors": [OperationError.from_dict(_item) for _item in obj["Errors"]] if obj.get("Errors") is not None else None
        })
        return _obj
