# coding: utf-8

"""
    CustomerManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.customer.key_value_entity_oflong_andint import KeyValueEntityOflongAndint
from typing_extensions import Self

class DismissNotificationsRequest(BaseModel):
    """
    DismissNotificationsRequest
    """ # noqa: E501
    notification_type_pairs: Optional[List[Optional[KeyValueEntityOflongAndint]]] = Field(default=None, alias="NotificationTypePairs")
    user_id: Optional[StrictInt] = Field(default=None, alias="UserId")
    __properties: ClassVar[List[str]] = ["NotificationTypePairs", "UserId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in notification_type_pairs (list)
        _items = []
        if self.notification_type_pairs:
            for _item_notification_type_pairs in self.notification_type_pairs:
                if _item_notification_type_pairs:
                    _items.append(_item_notification_type_pairs.to_dict())
            _dict['NotificationTypePairs'] = _items
        # set to None if notification_type_pairs (nullable) is None
        # and model_fields_set contains the field
        if self.notification_type_pairs is None and "notification_type_pairs" in self.model_fields_set:
            _dict['NotificationTypePairs'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['UserId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DismissNotificationsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "NotificationTypePairs": [KeyValueEntityOflongAndint.from_dict(_item) for _item in obj["NotificationTypePairs"]] if obj.get("NotificationTypePairs") is not None else None,
                        "UserId": obj.get("UserId") if obj.get("UserId") is not None else None
        })
        return _obj
