# coding: utf-8

"""
    CustomerManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class GetCustomersInfoRequest(BaseModel):
    """
    GetCustomersInfoRequest
    """ # noqa: E501
    customer_name_filter: Optional[StrictStr] = Field(default=None, alias="CustomerNameFilter")
    top_n: Optional[StrictInt] = Field(default=None, alias="TopN")
    __properties: ClassVar[List[str]] = ["CustomerNameFilter", "TopN"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if customer_name_filter (nullable) is None
        # and model_fields_set contains the field
        if self.customer_name_filter is None and "customer_name_filter" in self.model_fields_set:
            _dict['CustomerNameFilter'] = None

        # set to None if top_n (nullable) is None
        # and model_fields_set contains the field
        if self.top_n is None and "top_n" in self.model_fields_set:
            _dict['TopN'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetCustomersInfoRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CustomerNameFilter": obj.get("CustomerNameFilter") if obj.get("CustomerNameFilter") is not None else None,
                        "TopN": obj.get("TopN") if obj.get("TopN") is not None else None
        })
        return _obj
