# coding: utf-8

"""
    CustomerManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.customer.customer import Customer
from typing_extensions import Self

class GetAccessibleCustomerResponse(BaseModel):
    """
    GetAccessibleCustomerResponse
    """ # noqa: E501
    accessible_customer: Optional[Customer] = Field(default=None, alias="AccessibleCustomer")
    valid_fields: Optional[StrictInt] = Field(default=None, alias="ValidFields")
    __properties: ClassVar[List[str]] = ["AccessibleCustomer", "ValidFields"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of accessible_customer
        if self.accessible_customer:
            _dict['AccessibleCustomer'] = self.accessible_customer.to_dict()
        # set to None if accessible_customer (nullable) is None
        # and model_fields_set contains the field
        if self.accessible_customer is None and "accessible_customer" in self.model_fields_set:
            _dict['AccessibleCustomer'] = None

        # set to None if valid_fields (nullable) is None
        # and model_fields_set contains the field
        if self.valid_fields is None and "valid_fields" in self.model_fields_set:
            _dict['ValidFields'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAccessibleCustomerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AccessibleCustomer": Customer.from_dict(obj["AccessibleCustomer"]) if obj.get("AccessibleCustomer") is not None else None,
                        "ValidFields": obj.get("ValidFields") if obj.get("ValidFields") is not None else None
        })
        return _obj
