# coding: utf-8

"""
    CustomerManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self

class LanguageType(str, Enum):
    DANISH = 'Danish'

    DUTCH = 'Dutch'

    ENGLISH = 'English'

    FINNISH = 'Finnish'

    FRENCH = 'French'

    GERMAN = 'German'

    ITALIAN = 'Italian'

    JAPANESE = 'Japanese'

    NORWEGIAN = 'Norwegian'

    PORTUGUESE = 'Portuguese'

    SWEDISH = 'Swedish'

    SPANISH = 'Spanish'

    ARABIC = 'Arabic'

    HEBREW = 'Hebrew'

    KOREAN = 'Korean'

    RUSSIAN = 'Russian'

    TRADITIONALCHINESE = 'TraditionalChinese'

    SIMPLIFIEDCHINESE = 'SimplifiedChinese'

    THAI = 'Thai'

    TURKISH = 'Turkish'

    FILIPINO = 'Filipino'

    INDONESIAN = 'Indonesian'

    POLISH = 'Polish'

    VIETNAMESE = 'Vietnamese'

    MALAY = 'Malay'

    UKRAINIAN = 'Ukrainian'

    CZECH = 'Czech'

    ROMANIAN = 'Romanian'

    GREEK = 'Greek'

    HUNGARIAN = 'Hungarian'

    HINDI = 'Hindi'

    BULGARIAN = 'Bulgarian'

    LITHUANIAN = 'Lithuanian'

    CROATIAN = 'Croatian'

    LATVIAN = 'Latvian'

    SLOVENIAN = 'Slovenian'

	
    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LanguageType from a JSON string"""
        return cls(json.loads(json_str))


