# coding: utf-8

"""
    CustomerBillingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class DistributeCouponsRequest(BaseModel):
    """
    DistributeCouponsRequest
    """ # noqa: E501
    account_ids: Optional[List[StrictInt]] = Field(default=None, alias="AccountIds")
    class_name: Optional[StrictStr] = Field(default=None, alias="ClassName")
    feature_id: Optional[StrictInt] = Field(default=None, alias="FeatureId")
    send_notification: Optional[StrictBool] = Field(default=None, alias="SendNotification")
    __properties: ClassVar[List[str]] = ["AccountIds", "ClassName", "FeatureId", "SendNotification"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if account_ids (nullable) is None
        # and model_fields_set contains the field
        if self.account_ids is None and "account_ids" in self.model_fields_set:
            _dict['AccountIds'] = None

        # set to None if class_name (nullable) is None
        # and model_fields_set contains the field
        if self.class_name is None and "class_name" in self.model_fields_set:
            _dict['ClassName'] = None

        # set to None if feature_id (nullable) is None
        # and model_fields_set contains the field
        if self.feature_id is None and "feature_id" in self.model_fields_set:
            _dict['FeatureId'] = None

        # set to None if send_notification (nullable) is None
        # and model_fields_set contains the field
        if self.send_notification is None and "send_notification" in self.model_fields_set:
            _dict['SendNotification'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DistributeCouponsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AccountIds": obj.get("AccountIds"),
                        "ClassName": obj.get("ClassName") if obj.get("ClassName") is not None else None,
                        "FeatureId": obj.get("FeatureId") if obj.get("FeatureId") is not None else None,
                        "SendNotification": obj.get("SendNotification") if obj.get("SendNotification") is not None else None
        })
        return _obj
