# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class AutoApplyRecommendationsInfo(BaseModel):
    """
    AutoApplyRecommendationsInfo
    """ # noqa: E501
    recommendation_type: Optional[StrictStr] = Field(default=None, alias="RecommendationType")
    aar_opt_in_status: Optional[StrictBool] = Field(default=None, alias="AAROptInStatus")
    __properties: ClassVar[List[str]] = ["RecommendationType", "AAROptInStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if recommendation_type (nullable) is None
        # and model_fields_set contains the field
        if self.recommendation_type is None and "recommendation_type" in self.model_fields_set:
            _dict['RecommendationType'] = None

        # set to None if aar_opt_in_status (nullable) is None
        # and model_fields_set contains the field
        if self.aar_opt_in_status is None and "aar_opt_in_status" in self.model_fields_set:
            _dict['AAROptInStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoApplyRecommendationsInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "RecommendationType": obj.get("RecommendationType") if obj.get("RecommendationType") is not None else None,
                        "AAROptInStatus": obj.get("AAROptInStatus") if obj.get("AAROptInStatus") is not None else None
        })
        return _obj
