# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.adinsight.campaign_bid_landscape_point import CampaignBidLandscapePoint
from openapi_client.models.adinsight.campaign_bid_landscape_type import CampaignBidLandscapeType
from openapi_client.models.adinsight.day_month_and_year import DayMonthAndYear
from typing_extensions import Self

class CampaignBidLandscape(BaseModel):
    """
    CampaignBidLandscape
    """ # noqa: E501
    campaign_id: Optional[StrictStr] = Field(default=None, alias="CampaignId")
    campaign_bid_landscape_type: Optional[CampaignBidLandscapeType] = Field(default=None, alias="CampaignBidLandscapeType")
    start_date: Optional[DayMonthAndYear] = Field(default=None, alias="StartDate")
    end_date: Optional[DayMonthAndYear] = Field(default=None, alias="EndDate")
    campaign_bid_landscape_points: Optional[List[Optional[CampaignBidLandscapePoint]]] = Field(default=None, alias="CampaignBidLandscapePoints")
    __properties: ClassVar[List[str]] = ["CampaignId", "CampaignBidLandscapeType", "StartDate", "EndDate", "CampaignBidLandscapePoints"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of start_date
        if self.start_date:
            _dict['StartDate'] = self.start_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of end_date
        if self.end_date:
            _dict['EndDate'] = self.end_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in campaign_bid_landscape_points (list)
        _items = []
        if self.campaign_bid_landscape_points:
            for _item_campaign_bid_landscape_points in self.campaign_bid_landscape_points:
                if _item_campaign_bid_landscape_points:
                    _items.append(_item_campaign_bid_landscape_points.to_dict())
            _dict['CampaignBidLandscapePoints'] = _items
        # set to None if campaign_id (nullable) is None
        # and model_fields_set contains the field
        if self.campaign_id is None and "campaign_id" in self.model_fields_set:
            _dict['CampaignId'] = None

        # set to None if campaign_bid_landscape_type (nullable) is None
        # and model_fields_set contains the field
        if self.campaign_bid_landscape_type is None and "campaign_bid_landscape_type" in self.model_fields_set:
            _dict['CampaignBidLandscapeType'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['StartDate'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['EndDate'] = None

        # set to None if campaign_bid_landscape_points (nullable) is None
        # and model_fields_set contains the field
        if self.campaign_bid_landscape_points is None and "campaign_bid_landscape_points" in self.model_fields_set:
            _dict['CampaignBidLandscapePoints'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CampaignBidLandscape from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CampaignId": obj.get("CampaignId") if obj.get("CampaignId") is not None else None,
                        "CampaignBidLandscapeType": obj.get("CampaignBidLandscapeType") if obj.get("CampaignBidLandscapeType") is not None else None,
                        "StartDate": DayMonthAndYear.from_dict(obj["StartDate"]) if obj.get("StartDate") is not None else None,
                        "EndDate": DayMonthAndYear.from_dict(obj["EndDate"]) if obj.get("EndDate") is not None else None,
                        "CampaignBidLandscapePoints": [CampaignBidLandscapePoint.from_dict(_item) for _item in obj["CampaignBidLandscapePoints"]] if obj.get("CampaignBidLandscapePoints") is not None else None
        })
        return _obj
