# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.adinsight.entity_detail import EntityDetail
from openapi_client.models.adinsight.performance_insights_entity_type import PerformanceInsightsEntityType
from typing_extensions import Self

class EntityParameter(BaseModel):
    """
    EntityParameter
    """ # noqa: E501
    suggested_text: Optional[StrictStr] = Field(default=None, alias="SuggestedText")
    entity_type: Optional[PerformanceInsightsEntityType] = Field(default=None, alias="EntityType")
    entity_count: Optional[StrictInt] = Field(default=None, alias="EntityCount")
    entity_details: Optional[List[Optional[EntityDetail]]] = Field(default=None, alias="EntityDetails")
    type: Optional[StrictStr] = Field(default='Entities', alias="Type")
    __properties: ClassVar[List[str]] = ["SuggestedText", "EntityType", "EntityCount", "EntityDetails", "Type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	
    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())
	
    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entity_details (list)
        _items = []
        if self.entity_details:
            for _item_entity_details in self.entity_details:
                if _item_entity_details:
                    _items.append(_item_entity_details.to_dict())
            _dict['EntityDetails'] = _items
        # set to None if suggested_text (nullable) is None
        # and model_fields_set contains the field
        if self.suggested_text is None and "suggested_text" in self.model_fields_set:
            _dict['SuggestedText'] = None

        # set to None if entity_type (nullable) is None
        # and model_fields_set contains the field
        if self.entity_type is None and "entity_type" in self.model_fields_set:
            _dict['EntityType'] = None

        # set to None if entity_count (nullable) is None
        # and model_fields_set contains the field
        if self.entity_count is None and "entity_count" in self.model_fields_set:
            _dict['EntityCount'] = None

        # set to None if entity_details (nullable) is None
        # and model_fields_set contains the field
        if self.entity_details is None and "entity_details" in self.model_fields_set:
            _dict['EntityDetails'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "SuggestedText": obj.get("SuggestedText") if obj.get("SuggestedText") is not None else None,
                        "EntityType": obj.get("EntityType") if obj.get("EntityType") is not None else None,
                        "EntityCount": obj.get("EntityCount") if obj.get("EntityCount") is not None else None,
                        "EntityDetails": [EntityDetail.from_dict(_item) for _item in obj["EntityDetails"]] if obj.get("EntityDetails") is not None else None,
                        "Type": obj.get("Type") if obj.get("Type") is not None else 'Entities'
        })
        return _obj
