# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class Feed(BaseModel):
    """
    Feed
    """ # noqa: E501
    store_id: Optional[StrictStr] = Field(default=None, alias="StoreId")
    feed_id: Optional[StrictStr] = Field(default=None, alias="FeedId")
    feed_type: Optional[StrictStr] = Field(default=None, alias="FeedType")
    __properties: ClassVar[List[str]] = ["StoreId", "FeedId", "FeedType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if store_id (nullable) is None
        # and model_fields_set contains the field
        if self.store_id is None and "store_id" in self.model_fields_set:
            _dict['StoreId'] = None

        # set to None if feed_id (nullable) is None
        # and model_fields_set contains the field
        if self.feed_id is None and "feed_id" in self.model_fields_set:
            _dict['FeedId'] = None

        # set to None if feed_type (nullable) is None
        # and model_fields_set contains the field
        if self.feed_type is None and "feed_type" in self.model_fields_set:
            _dict['FeedType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Feed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "StoreId": obj.get("StoreId") if obj.get("StoreId") is not None else None,
                        "FeedId": obj.get("FeedId") if obj.get("FeedId") is not None else None,
                        "FeedType": obj.get("FeedType") if obj.get("FeedType") is not None else None
        })
        return _obj
