# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.adinsight.keyword_search_count import KeywordSearchCount
from typing_extensions import Self

class GetHistoricalSearchCountResponse(BaseModel):
    """
    GetHistoricalSearchCountResponse
    """ # noqa: E501
    keyword_search_counts: Optional[List[Optional[KeywordSearchCount]]] = Field(default=None, alias="KeywordSearchCounts")
    __properties: ClassVar[List[str]] = ["KeywordSearchCounts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in keyword_search_counts (list)
        _items = []
        if self.keyword_search_counts:
            for _item_keyword_search_counts in self.keyword_search_counts:
                if _item_keyword_search_counts:
                    _items.append(_item_keyword_search_counts.to_dict())
            _dict['KeywordSearchCounts'] = _items
        # set to None if keyword_search_counts (nullable) is None
        # and model_fields_set contains the field
        if self.keyword_search_counts is None and "keyword_search_counts" in self.model_fields_set:
            _dict['KeywordSearchCounts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetHistoricalSearchCountResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "KeywordSearchCounts": [KeywordSearchCount.from_dict(_item) for _item in obj["KeywordSearchCounts"]] if obj.get("KeywordSearchCounts") is not None else None
        })
        return _obj
