# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.adinsight.auto_apply_recommendations_info import AutoApplyRecommendationsInfo
from typing_extensions import Self

class GetAutoApplyOptInStatusResponse(BaseModel):
    """
    GetAutoApplyOptInStatusResponse
    """ # noqa: E501
    auto_apply_recommendations_status: Optional[List[Optional[AutoApplyRecommendationsInfo]]] = Field(default=None, alias="AutoApplyRecommendationsStatus")
    __properties: ClassVar[List[str]] = ["AutoApplyRecommendationsStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in auto_apply_recommendations_status (list)
        _items = []
        if self.auto_apply_recommendations_status:
            for _item_auto_apply_recommendations_status in self.auto_apply_recommendations_status:
                if _item_auto_apply_recommendations_status:
                    _items.append(_item_auto_apply_recommendations_status.to_dict())
            _dict['AutoApplyRecommendationsStatus'] = _items
        # set to None if auto_apply_recommendations_status (nullable) is None
        # and model_fields_set contains the field
        if self.auto_apply_recommendations_status is None and "auto_apply_recommendations_status" in self.model_fields_set:
            _dict['AutoApplyRecommendationsStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAutoApplyOptInStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AutoApplyRecommendationsStatus": [AutoApplyRecommendationsInfo.from_dict(_item) for _item in obj["AutoApplyRecommendationsStatus"]] if obj.get("AutoApplyRecommendationsStatus") is not None else None
        })
        return _obj
