# coding: utf-8

"""
    AdInsightService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.adinsight.estimated_position_and_traffic import EstimatedPositionAndTraffic
from typing_extensions import Self

class KeywordEstimatedPosition(BaseModel):
    """
    KeywordEstimatedPosition
    """ # noqa: E501
    keyword: Optional[StrictStr] = Field(default=None, alias="Keyword")
    estimated_positions: Optional[List[Optional[EstimatedPositionAndTraffic]]] = Field(default=None, alias="EstimatedPositions")
    __properties: ClassVar[List[str]] = ["Keyword", "EstimatedPositions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in estimated_positions (list)
        _items = []
        if self.estimated_positions:
            for _item_estimated_positions in self.estimated_positions:
                if _item_estimated_positions:
                    _items.append(_item_estimated_positions.to_dict())
            _dict['EstimatedPositions'] = _items
        # set to None if keyword (nullable) is None
        # and model_fields_set contains the field
        if self.keyword is None and "keyword" in self.model_fields_set:
            _dict['Keyword'] = None

        # set to None if estimated_positions (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_positions is None and "estimated_positions" in self.model_fields_set:
            _dict['EstimatedPositions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KeywordEstimatedPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Keyword": obj.get("Keyword") if obj.get("Keyword") is not None else None,
                        "EstimatedPositions": [EstimatedPositionAndTraffic.from_dict(_item) for _item in obj["EstimatedPositions"]] if obj.get("EstimatedPositions") is not None else None
        })
        return _obj
