# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.ad_extension import AdExtension
from openapi_client.models.campaign.ad_extension_editorial_status import AdExtensionEditorialStatus
from openapi_client.models.campaign.association_type import AssociationType
from typing_extensions import Self

class AdExtensionAssociation(BaseModel):
    """
    AdExtensionAssociation
    """ # noqa: E501
    entity_id: Optional[StrictStr] = Field(default=None, alias="EntityId")
    association_type: Optional[AssociationType] = Field(default=None, alias="AssociationType")
    ad_extension: Optional[AdExtension] = Field(default=None, alias="AdExtension")
    editorial_status: Optional[AdExtensionEditorialStatus] = Field(default=None, alias="EditorialStatus")
    __properties: ClassVar[List[str]] = ["EntityId", "AssociationType", "AdExtension", "EditorialStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ad_extension
        if self.ad_extension:
            _dict['AdExtension'] = self.ad_extension.to_dict()
        # set to None if entity_id (nullable) is None
        # and model_fields_set contains the field
        if self.entity_id is None and "entity_id" in self.model_fields_set:
            _dict['EntityId'] = None

        # set to None if association_type (nullable) is None
        # and model_fields_set contains the field
        if self.association_type is None and "association_type" in self.model_fields_set:
            _dict['AssociationType'] = None

        # set to None if ad_extension (nullable) is None
        # and model_fields_set contains the field
        if self.ad_extension is None and "ad_extension" in self.model_fields_set:
            _dict['AdExtension'] = None

        # set to None if editorial_status (nullable) is None
        # and model_fields_set contains the field
        if self.editorial_status is None and "editorial_status" in self.model_fields_set:
            _dict['EditorialStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdExtensionAssociation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "EntityId": obj.get("EntityId") if obj.get("EntityId") is not None else None,
                        "AssociationType": obj.get("AssociationType") if obj.get("AssociationType") is not None else None,
                        "AdExtension": AdExtension.from_dict(obj["AdExtension"]) if obj.get("AdExtension") is not None else None,
                        "EditorialStatus": obj.get("EditorialStatus") if obj.get("EditorialStatus") is not None else None
        })
        return _obj
