# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.campaign_criterion import CampaignCriterion
from openapi_client.models.campaign.campaign_criterion_type import CampaignCriterionType
from typing_extensions import Self

class AddCampaignCriterionsRequest(BaseModel):
    """
    AddCampaignCriterionsRequest
    """ # noqa: E501
    campaign_criterions: Optional[List[Optional[CampaignCriterion]]] = Field(default=None, alias="CampaignCriterions")
    criterion_type: Optional[CampaignCriterionType] = Field(default=None, alias="CriterionType")
    __properties: ClassVar[List[str]] = ["CampaignCriterions", "CriterionType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in campaign_criterions (list)
        _items = []
        if self.campaign_criterions:
            for _item_campaign_criterions in self.campaign_criterions:
                if _item_campaign_criterions:
                    _items.append(_item_campaign_criterions.to_dict())
            _dict['CampaignCriterions'] = _items
        # set to None if campaign_criterions (nullable) is None
        # and model_fields_set contains the field
        if self.campaign_criterions is None and "campaign_criterions" in self.model_fields_set:
            _dict['CampaignCriterions'] = None

        # set to None if criterion_type (nullable) is None
        # and model_fields_set contains the field
        if self.criterion_type is None and "criterion_type" in self.model_fields_set:
            _dict['CriterionType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddCampaignCriterionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CampaignCriterions": [CampaignCriterion.from_dict(_item) for _item in obj["CampaignCriterions"]] if obj.get("CampaignCriterions") is not None else None,
                        "CriterionType": obj.get("CriterionType") if obj.get("CriterionType") is not None else None
        })
        return _obj
