# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class AudienceGroupAssetGroupAssociation(BaseModel):
    """
    AudienceGroupAssetGroupAssociation
    """ # noqa: E501
    asset_group_id: Optional[StrictStr] = Field(default=None, alias="AssetGroupId")
    audience_group_id: Optional[StrictStr] = Field(default=None, alias="AudienceGroupId")
    __properties: ClassVar[List[str]] = ["AssetGroupId", "AudienceGroupId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if asset_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.asset_group_id is None and "asset_group_id" in self.model_fields_set:
            _dict['AssetGroupId'] = None

        # set to None if audience_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.audience_group_id is None and "audience_group_id" in self.model_fields_set:
            _dict['AudienceGroupId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AudienceGroupAssetGroupAssociation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AssetGroupId": obj.get("AssetGroupId") if obj.get("AssetGroupId") is not None else None,
                        "AudienceGroupId": obj.get("AudienceGroupId") if obj.get("AudienceGroupId") is not None else None
        })
        return _obj
