# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

class BiddingScheme(BaseModel):
    """
    BiddingScheme
    """

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, **kwargs):
        if 'type' not in kwargs and 'Type' not in kwargs:
            class_name = self.__class__.__name__
            type_mapping = [
                ('CommissionBiddingScheme', 'CommissionBiddingScheme'),
                ('CostPerSaleBiddingScheme', 'CostPerSale'),
                ('EnhancedCpcBiddingScheme', 'EnhancedCpc'),
                ('InheritFromParentBiddingScheme', 'InheritFromParent'),
                ('ManualCpaBiddingScheme', 'ManualCpaBiddingScheme'),
                ('ManualCpcBiddingScheme', 'ManualCpc'),
                ('ManualCpmBiddingScheme', 'ManualCpm'),
                ('ManualCpvBiddingScheme', 'ManualCpv'),
                ('MaxClicksBiddingScheme', 'MaxClicks'),
                ('MaxConversionValueBiddingScheme', 'MaxConversionValueBiddingScheme'),
                ('MaxConversionsBiddingScheme', 'MaxConversions'),
                ('MaxRoasBiddingScheme', 'MaxRoasBiddingScheme'),
                ('PercentCpcBiddingScheme', 'PercentCpcBiddingScheme'),
                ('TargetCpaBiddingScheme', 'TargetCpa'),
                ('TargetImpressionShareBiddingScheme', 'TargetImpressionShareBiddingScheme'),
                ('TargetRoasBiddingScheme', 'TargetRoasBiddingScheme'),
                ('CostPerSaleBiddingScheme', 'CostPerSaleBiddingScheme'),
                ('EnhancedCpcBiddingScheme', 'EnhancedCpcBiddingScheme'),
                ('InheritFromParentBiddingScheme', 'InheritFromParentBiddingScheme'),
                ('ManualCpcBiddingScheme', 'ManualCpcBiddingScheme'),
                ('ManualCpmBiddingScheme', 'ManualCpmBiddingScheme'),
                ('ManualCpvBiddingScheme', 'ManualCpvBiddingScheme'),
                ('MaxClicksBiddingScheme', 'MaxClicksBiddingScheme'),
                ('MaxConversionsBiddingScheme', 'MaxConversionsBiddingScheme'),
                ('TargetCpaBiddingScheme', 'TargetCpaBiddingScheme'),
            ]
            for key, value in type_mapping:
                if class_name == key:
                    kwargs['type'] = value
                    break
        super().__init__(**kwargs)

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Create an instance of BiddingScheme from a JSON string"""
        return cls.from_dict(json.loads(json_str))
    
    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias."""
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        
        # set to None if type (nullable) is None and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BiddingScheme from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # Try to determine the specific media type from the Type field
        type = obj.get("Type")
        
        # Import here to avoid circular imports
        if type == "CommissionBiddingScheme":
            from openapi_client.models.campaign.commission_bidding_scheme import CommissionBiddingScheme
            return CommissionBiddingScheme.from_dict(obj)
        
        if type == "CostPerSale":
            from openapi_client.models.campaign.cost_per_sale_bidding_scheme import CostPerSaleBiddingScheme
            return CostPerSaleBiddingScheme.from_dict(obj)
        
        if type == "EnhancedCpc":
            from openapi_client.models.campaign.enhanced_cpc_bidding_scheme import EnhancedCpcBiddingScheme
            return EnhancedCpcBiddingScheme.from_dict(obj)
        
        if type == "InheritFromParent":
            from openapi_client.models.campaign.inherit_from_parent_bidding_scheme import InheritFromParentBiddingScheme
            return InheritFromParentBiddingScheme.from_dict(obj)
        
        if type == "ManualCpaBiddingScheme":
            from openapi_client.models.campaign.manual_cpa_bidding_scheme import ManualCpaBiddingScheme
            return ManualCpaBiddingScheme.from_dict(obj)
        
        if type == "ManualCpc":
            from openapi_client.models.campaign.manual_cpc_bidding_scheme import ManualCpcBiddingScheme
            return ManualCpcBiddingScheme.from_dict(obj)
        
        if type == "ManualCpm":
            from openapi_client.models.campaign.manual_cpm_bidding_scheme import ManualCpmBiddingScheme
            return ManualCpmBiddingScheme.from_dict(obj)
        
        if type == "ManualCpv":
            from openapi_client.models.campaign.manual_cpv_bidding_scheme import ManualCpvBiddingScheme
            return ManualCpvBiddingScheme.from_dict(obj)
        
        if type == "MaxClicks":
            from openapi_client.models.campaign.max_clicks_bidding_scheme import MaxClicksBiddingScheme
            return MaxClicksBiddingScheme.from_dict(obj)
        
        if type == "MaxConversionValueBiddingScheme":
            from openapi_client.models.campaign.max_conversion_value_bidding_scheme import MaxConversionValueBiddingScheme
            return MaxConversionValueBiddingScheme.from_dict(obj)
        
        if type == "MaxConversions":
            from openapi_client.models.campaign.max_conversions_bidding_scheme import MaxConversionsBiddingScheme
            return MaxConversionsBiddingScheme.from_dict(obj)
        
        if type == "MaxRoasBiddingScheme":
            from openapi_client.models.campaign.max_roas_bidding_scheme import MaxRoasBiddingScheme
            return MaxRoasBiddingScheme.from_dict(obj)
        
        if type == "PercentCpcBiddingScheme":
            from openapi_client.models.campaign.percent_cpc_bidding_scheme import PercentCpcBiddingScheme
            return PercentCpcBiddingScheme.from_dict(obj)
        
        if type == "TargetCpa":
            from openapi_client.models.campaign.target_cpa_bidding_scheme import TargetCpaBiddingScheme
            return TargetCpaBiddingScheme.from_dict(obj)
        
        if type == "TargetImpressionShareBiddingScheme":
            from openapi_client.models.campaign.target_impression_share_bidding_scheme import TargetImpressionShareBiddingScheme
            return TargetImpressionShareBiddingScheme.from_dict(obj)
        
        if type == "TargetRoasBiddingScheme":
            from openapi_client.models.campaign.target_roas_bidding_scheme import TargetRoasBiddingScheme
            return TargetRoasBiddingScheme.from_dict(obj)
        
        if type == "CostPerSaleBiddingScheme":
            from openapi_client.models.campaign.cost_per_sale_bidding_scheme import CostPerSaleBiddingScheme
            return CostPerSaleBiddingScheme.from_dict(obj)
        
        if type == "EnhancedCpcBiddingScheme":
            from openapi_client.models.campaign.enhanced_cpc_bidding_scheme import EnhancedCpcBiddingScheme
            return EnhancedCpcBiddingScheme.from_dict(obj)
        
        if type == "InheritFromParentBiddingScheme":
            from openapi_client.models.campaign.inherit_from_parent_bidding_scheme import InheritFromParentBiddingScheme
            return InheritFromParentBiddingScheme.from_dict(obj)
        
        if type == "ManualCpcBiddingScheme":
            from openapi_client.models.campaign.manual_cpc_bidding_scheme import ManualCpcBiddingScheme
            return ManualCpcBiddingScheme.from_dict(obj)
        
        if type == "ManualCpmBiddingScheme":
            from openapi_client.models.campaign.manual_cpm_bidding_scheme import ManualCpmBiddingScheme
            return ManualCpmBiddingScheme.from_dict(obj)
        
        if type == "ManualCpvBiddingScheme":
            from openapi_client.models.campaign.manual_cpv_bidding_scheme import ManualCpvBiddingScheme
            return ManualCpvBiddingScheme.from_dict(obj)
        
        if type == "MaxClicksBiddingScheme":
            from openapi_client.models.campaign.max_clicks_bidding_scheme import MaxClicksBiddingScheme
            return MaxClicksBiddingScheme.from_dict(obj)
        
        if type == "MaxConversionsBiddingScheme":
            from openapi_client.models.campaign.max_conversions_bidding_scheme import MaxConversionsBiddingScheme
            return MaxConversionsBiddingScheme.from_dict(obj)
        
        if type == "TargetCpaBiddingScheme":
            from openapi_client.models.campaign.target_cpa_bidding_scheme import TargetCpaBiddingScheme
            return TargetCpaBiddingScheme.from_dict(obj)
        
        
        # Fallback to base class
        _obj = cls.model_validate({
            "Type": obj.get("Type") if obj.get("Type") is not None else None
        })
        return _obj
