# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.company_name import CompanyName
from openapi_client.models.campaign.linked_in_segment_status import LinkedInSegmentStatus
from openapi_client.models.campaign.profile_type import ProfileType
from typing_extensions import Self
from openapi_client.models.campaign.linked_in_segment import LinkedInSegment
class CompanyList(LinkedInSegment):
    """
    CompanyList
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    type: Optional[ProfileType] = Field(default=None, alias="Type")
    status: Optional[LinkedInSegmentStatus] = Field(default=None, alias="Status")
    reach: Optional[StrictStr] = Field(default=None, alias="Reach")
    company_names: Optional[List[Optional[CompanyName]]] = Field(default=None, alias="CompanyNames")
    total: Optional[StrictInt] = Field(default=None, alias="Total")
    matched: Optional[StrictInt] = Field(default=None, alias="Matched")
    __properties: ClassVar[List[str]] = ["Id", "Name", "Type", "Status", "Reach", "CompanyNames", "Total", "Matched"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())
	
    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyList from a JSON string"""
        return cls.from_dict(json.loads(json_str))
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in company_names (list)
        _items = []
        if self.company_names:
            for _item_company_names in self.company_names:
                if _item_company_names:
                    _items.append(_item_company_names.to_dict())
            _dict['CompanyNames'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['Name'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['Status'] = None

        # set to None if reach (nullable) is None
        # and model_fields_set contains the field
        if self.reach is None and "reach" in self.model_fields_set:
            _dict['Reach'] = None

        # set to None if company_names (nullable) is None
        # and model_fields_set contains the field
        if self.company_names is None and "company_names" in self.model_fields_set:
            _dict['CompanyNames'] = None

        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['Total'] = None

        # set to None if matched (nullable) is None
        # and model_fields_set contains the field
        if self.matched is None and "matched" in self.model_fields_set:
            _dict['Matched'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id") if obj.get("Id") is not None else None,
                        "Name": obj.get("Name") if obj.get("Name") is not None else None,
                        "Type": obj.get("Type") if obj.get("Type") is not None else None,
                        "Status": obj.get("Status") if obj.get("Status") is not None else None,
                        "Reach": obj.get("Reach") if obj.get("Reach") is not None else None,
                        "CompanyNames": [CompanyName.from_dict(_item) for _item in obj["CompanyNames"]] if obj.get("CompanyNames") is not None else None,
                        "Total": obj.get("Total") if obj.get("Total") is not None else None,
                        "Matched": obj.get("Matched") if obj.get("Matched") is not None else None
        })
        return _obj
