# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.customer_list_action_type import CustomerListActionType
from openapi_client.models.campaign.customer_list_item_sub_type import CustomerListItemSubType
from typing_extensions import Self

class CustomerListUserData(BaseModel):
    """
    CustomerListUserData
    """ # noqa: E501
    audience_id: Optional[StrictStr] = Field(default=None, alias="AudienceId")
    customer_list_items: Optional[List[StrictStr]] = Field(default=None, alias="CustomerListItems")
    customer_list_item_sub_type: Optional[CustomerListItemSubType] = Field(default=None, alias="CustomerListItemSubType")
    action_type: Optional[CustomerListActionType] = Field(default=None, alias="ActionType")
    __properties: ClassVar[List[str]] = ["AudienceId", "CustomerListItems", "CustomerListItemSubType", "ActionType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if audience_id (nullable) is None
        # and model_fields_set contains the field
        if self.audience_id is None and "audience_id" in self.model_fields_set:
            _dict['AudienceId'] = None

        # set to None if customer_list_items (nullable) is None
        # and model_fields_set contains the field
        if self.customer_list_items is None and "customer_list_items" in self.model_fields_set:
            _dict['CustomerListItems'] = None

        # set to None if customer_list_item_sub_type (nullable) is None
        # and model_fields_set contains the field
        if self.customer_list_item_sub_type is None and "customer_list_item_sub_type" in self.model_fields_set:
            _dict['CustomerListItemSubType'] = None

        # set to None if action_type (nullable) is None
        # and model_fields_set contains the field
        if self.action_type is None and "action_type" in self.model_fields_set:
            _dict['ActionType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerListUserData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AudienceId": obj.get("AudienceId") if obj.get("AudienceId") is not None else None,
                        "CustomerListItems": obj.get("CustomerListItems"),
                        "CustomerListItemSubType": obj.get("CustomerListItemSubType") if obj.get("CustomerListItemSubType") is not None else None,
                        "ActionType": obj.get("ActionType") if obj.get("ActionType") is not None else None
        })
        return _obj
