# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.number_operator import NumberOperator
from openapi_client.models.campaign.string_operator import StringOperator
from typing_extensions import Self

class CustomEventsRule(BaseModel):
    """
    CustomEventsRule
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default='CustomEvents', alias="Type")
    category_operator: Optional[StringOperator] = Field(default=None, alias="CategoryOperator")
    category: Optional[StrictStr] = Field(default=None, alias="Category")
    action_operator: Optional[StringOperator] = Field(default=None, alias="ActionOperator")
    action: Optional[StrictStr] = Field(default=None, alias="Action")
    label_operator: Optional[StringOperator] = Field(default=None, alias="LabelOperator")
    label: Optional[StrictStr] = Field(default=None, alias="Label")
    value_operator: Optional[NumberOperator] = Field(default=None, alias="ValueOperator")
    value: Optional[StrictFloat] = Field(default=None, alias="Value")
    __properties: ClassVar[List[str]] = ["Type", "CategoryOperator", "Category", "ActionOperator", "Action", "LabelOperator", "Label", "ValueOperator", "Value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	
    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())
	
    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomEventsRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        # set to None if category_operator (nullable) is None
        # and model_fields_set contains the field
        if self.category_operator is None and "category_operator" in self.model_fields_set:
            _dict['CategoryOperator'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['Category'] = None

        # set to None if action_operator (nullable) is None
        # and model_fields_set contains the field
        if self.action_operator is None and "action_operator" in self.model_fields_set:
            _dict['ActionOperator'] = None

        # set to None if action (nullable) is None
        # and model_fields_set contains the field
        if self.action is None and "action" in self.model_fields_set:
            _dict['Action'] = None

        # set to None if label_operator (nullable) is None
        # and model_fields_set contains the field
        if self.label_operator is None and "label_operator" in self.model_fields_set:
            _dict['LabelOperator'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['Label'] = None

        # set to None if value_operator (nullable) is None
        # and model_fields_set contains the field
        if self.value_operator is None and "value_operator" in self.model_fields_set:
            _dict['ValueOperator'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['Value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomEventsRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Type": obj.get("Type") if obj.get("Type") is not None else 'CustomEvents',
                        "CategoryOperator": obj.get("CategoryOperator") if obj.get("CategoryOperator") is not None else None,
                        "Category": obj.get("Category") if obj.get("Category") is not None else None,
                        "ActionOperator": obj.get("ActionOperator") if obj.get("ActionOperator") is not None else None,
                        "Action": obj.get("Action") if obj.get("Action") is not None else None,
                        "LabelOperator": obj.get("LabelOperator") if obj.get("LabelOperator") is not None else None,
                        "Label": obj.get("Label") if obj.get("Label") is not None else None,
                        "ValueOperator": obj.get("ValueOperator") if obj.get("ValueOperator") is not None else None,
                        "Value": obj.get("Value") if obj.get("Value") is not None else None
        })
        return _obj
