# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class CustomerAccountShareAssociation(BaseModel):
    """
    CustomerAccountShareAssociation
    """ # noqa: E501
    usage_type: Optional[StrictStr] = Field(default=None, alias="UsageType")
    association_count: Optional[StrictStr] = Field(default=None, alias="AssociationCount")
    __properties: ClassVar[List[str]] = ["UsageType", "AssociationCount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if usage_type (nullable) is None
        # and model_fields_set contains the field
        if self.usage_type is None and "usage_type" in self.model_fields_set:
            _dict['UsageType'] = None

        # set to None if association_count (nullable) is None
        # and model_fields_set contains the field
        if self.association_count is None and "association_count" in self.model_fields_set:
            _dict['AssociationCount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerAccountShareAssociation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "UsageType": obj.get("UsageType") if obj.get("UsageType") is not None else None,
                        "AssociationCount": obj.get("AssociationCount") if obj.get("AssociationCount") is not None else None
        })
        return _obj
