# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.campaign_conversion_goal import CampaignConversionGoal
from typing_extensions import Self

class DeleteCampaignConversionGoalsRequest(BaseModel):
    """
    DeleteCampaignConversionGoalsRequest
    """ # noqa: E501
    campaign_conversion_goal: Optional[List[Optional[CampaignConversionGoal]]] = Field(default=None, alias="CampaignConversionGoal")
    __properties: ClassVar[List[str]] = ["CampaignConversionGoal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in campaign_conversion_goal (list)
        _items = []
        if self.campaign_conversion_goal:
            for _item_campaign_conversion_goal in self.campaign_conversion_goal:
                if _item_campaign_conversion_goal:
                    _items.append(_item_campaign_conversion_goal.to_dict())
            _dict['CampaignConversionGoal'] = _items
        # set to None if campaign_conversion_goal (nullable) is None
        # and model_fields_set contains the field
        if self.campaign_conversion_goal is None and "campaign_conversion_goal" in self.model_fields_set:
            _dict['CampaignConversionGoal'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeleteCampaignConversionGoalsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CampaignConversionGoal": [CampaignConversionGoal.from_dict(_item) for _item in obj["CampaignConversionGoal"]] if obj.get("CampaignConversionGoal") is not None else None
        })
        return _obj
