# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class EditorialReason(BaseModel):
    """
    EditorialReason
    """ # noqa: E501
    reason_code: Optional[StrictInt] = Field(default=None, alias="ReasonCode")
    location: Optional[StrictStr] = Field(default=None, alias="Location")
    term: Optional[StrictStr] = Field(default=None, alias="Term")
    publisher_countries: Optional[List[StrictStr]] = Field(default=None, alias="PublisherCountries")
    __properties: ClassVar[List[str]] = ["ReasonCode", "Location", "Term", "PublisherCountries"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason_code (nullable) is None
        # and model_fields_set contains the field
        if self.reason_code is None and "reason_code" in self.model_fields_set:
            _dict['ReasonCode'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['Location'] = None

        # set to None if term (nullable) is None
        # and model_fields_set contains the field
        if self.term is None and "term" in self.model_fields_set:
            _dict['Term'] = None

        # set to None if publisher_countries (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_countries is None and "publisher_countries" in self.model_fields_set:
            _dict['PublisherCountries'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EditorialReason from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ReasonCode": obj.get("ReasonCode") if obj.get("ReasonCode") is not None else None,
                        "Location": obj.get("Location") if obj.get("Location") is not None else None,
                        "Term": obj.get("Term") if obj.get("Term") is not None else None,
                        "PublisherCountries": obj.get("PublisherCountries")
        })
        return _obj
