# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class GetNegativeKeywordsByEntityIdsRequest(BaseModel):
    """
    GetNegativeKeywordsByEntityIdsRequest
    """ # noqa: E501
    entity_type: Optional[StrictStr] = Field(default=None, alias="EntityType")
    entity_ids: Optional[List[StrictStr]] = Field(default=None, alias="EntityIds")
    parent_entity_id: Optional[StrictStr] = Field(default=None, alias="ParentEntityId")
    __properties: ClassVar[List[str]] = ["EntityType", "EntityIds", "ParentEntityId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if entity_type (nullable) is None
        # and model_fields_set contains the field
        if self.entity_type is None and "entity_type" in self.model_fields_set:
            _dict['EntityType'] = None

        # set to None if entity_ids (nullable) is None
        # and model_fields_set contains the field
        if self.entity_ids is None and "entity_ids" in self.model_fields_set:
            _dict['EntityIds'] = None

        # set to None if parent_entity_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_entity_id is None and "parent_entity_id" in self.model_fields_set:
            _dict['ParentEntityId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetNegativeKeywordsByEntityIdsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "EntityType": obj.get("EntityType") if obj.get("EntityType") is not None else None,
                        "EntityIds": obj.get("EntityIds"),
                        "ParentEntityId": obj.get("ParentEntityId") if obj.get("ParentEntityId") is not None else None
        })
        return _obj
