# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.batch_error import BatchError
from openapi_client.models.campaign.import_job import ImportJob
from typing_extensions import Self

class GetImportJobsByIdsResponse(BaseModel):
    """
    GetImportJobsByIdsResponse
    """ # noqa: E501
    import_jobs: Optional[List[Optional[ImportJob]]] = Field(default=None, alias="ImportJobs")
    partial_errors: Optional[List[Optional[BatchError]]] = Field(default=None, alias="PartialErrors")
    __properties: ClassVar[List[str]] = ["ImportJobs", "PartialErrors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in import_jobs (list)
        _items = []
        if self.import_jobs:
            for _item_import_jobs in self.import_jobs:
                if _item_import_jobs:
                    _items.append(_item_import_jobs.to_dict())
            _dict['ImportJobs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in partial_errors (list)
        _items = []
        if self.partial_errors:
            for _item_partial_errors in self.partial_errors:
                if _item_partial_errors:
                    _items.append(_item_partial_errors.to_dict())
            _dict['PartialErrors'] = _items
        # set to None if import_jobs (nullable) is None
        # and model_fields_set contains the field
        if self.import_jobs is None and "import_jobs" in self.model_fields_set:
            _dict['ImportJobs'] = None

        # set to None if partial_errors (nullable) is None
        # and model_fields_set contains the field
        if self.partial_errors is None and "partial_errors" in self.model_fields_set:
            _dict['PartialErrors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetImportJobsByIdsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ImportJobs": [ImportJob.from_dict(_item) for _item in obj["ImportJobs"]] if obj.get("ImportJobs") is not None else None,
                        "PartialErrors": [BatchError.from_dict(_item) for _item in obj["PartialErrors"]] if obj.get("PartialErrors") is not None else None
        })
        return _obj
