# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.account_migration_statuses_info import AccountMigrationStatusesInfo
from typing_extensions import Self

class GetAccountMigrationStatusesResponse(BaseModel):
    """
    GetAccountMigrationStatusesResponse
    """ # noqa: E501
    migration_statuses: Optional[List[Optional[AccountMigrationStatusesInfo]]] = Field(default=None, alias="MigrationStatuses")
    __properties: ClassVar[List[str]] = ["MigrationStatuses"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in migration_statuses (list)
        _items = []
        if self.migration_statuses:
            for _item_migration_statuses in self.migration_statuses:
                if _item_migration_statuses:
                    _items.append(_item_migration_statuses.to_dict())
            _dict['MigrationStatuses'] = _items
        # set to None if migration_statuses (nullable) is None
        # and model_fields_set contains the field
        if self.migration_statuses is None and "migration_statuses" in self.model_fields_set:
            _dict['MigrationStatuses'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAccountMigrationStatusesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "MigrationStatuses": [AccountMigrationStatusesInfo.from_dict(_item) for _item in obj["MigrationStatuses"]] if obj.get("MigrationStatuses") is not None else None
        })
        return _obj
