# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.company_size_category import CompanySizeCategory
from typing_extensions import Self

class LinkedInCompanyData(BaseModel):
    """
    LinkedInCompanyData
    """ # noqa: E501
    company_id: Optional[StrictStr] = Field(default=None, alias="CompanyId")
    company_name: Optional[StrictStr] = Field(default=None, alias="CompanyName")
    company_logo: Optional[StrictStr] = Field(default=None, alias="CompanyLogo")
    industry: Optional[StrictStr] = Field(default=None, alias="Industry")
    company_size: Optional[StrictStr] = Field(default=None, alias="CompanySize")
    company_size_category: Optional[CompanySizeCategory] = Field(default=None, alias="CompanySizeCategory")
    company_url: Optional[StrictStr] = Field(default=None, alias="CompanyUrl")
    __properties: ClassVar[List[str]] = ["CompanyId", "CompanyName", "CompanyLogo", "Industry", "CompanySize", "CompanySizeCategory", "CompanyUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if company_id (nullable) is None
        # and model_fields_set contains the field
        if self.company_id is None and "company_id" in self.model_fields_set:
            _dict['CompanyId'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['CompanyName'] = None

        # set to None if company_logo (nullable) is None
        # and model_fields_set contains the field
        if self.company_logo is None and "company_logo" in self.model_fields_set:
            _dict['CompanyLogo'] = None

        # set to None if industry (nullable) is None
        # and model_fields_set contains the field
        if self.industry is None and "industry" in self.model_fields_set:
            _dict['Industry'] = None

        # set to None if company_size (nullable) is None
        # and model_fields_set contains the field
        if self.company_size is None and "company_size" in self.model_fields_set:
            _dict['CompanySize'] = None

        # set to None if company_size_category (nullable) is None
        # and model_fields_set contains the field
        if self.company_size_category is None and "company_size_category" in self.model_fields_set:
            _dict['CompanySizeCategory'] = None

        # set to None if company_url (nullable) is None
        # and model_fields_set contains the field
        if self.company_url is None and "company_url" in self.model_fields_set:
            _dict['CompanyUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LinkedInCompanyData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CompanyId": obj.get("CompanyId") if obj.get("CompanyId") is not None else None,
                        "CompanyName": obj.get("CompanyName") if obj.get("CompanyName") is not None else None,
                        "CompanyLogo": obj.get("CompanyLogo") if obj.get("CompanyLogo") is not None else None,
                        "Industry": obj.get("Industry") if obj.get("Industry") is not None else None,
                        "CompanySize": obj.get("CompanySize") if obj.get("CompanySize") is not None else None,
                        "CompanySizeCategory": obj.get("CompanySizeCategory") if obj.get("CompanySizeCategory") is not None else None,
                        "CompanyUrl": obj.get("CompanyUrl") if obj.get("CompanyUrl") is not None else None
        })
        return _obj
