# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class LocationCriterion(BaseModel):
    """
    LocationCriterion
    """ # noqa: E501
    location_id: Optional[StrictStr] = Field(default=None, alias="LocationId")
    location_type: Optional[StrictStr] = Field(default=None, alias="LocationType")
    display_name: Optional[StrictStr] = Field(default=None, alias="DisplayName")
    enclosed_location_ids: Optional[List[StrictStr]] = Field(default=None, alias="EnclosedLocationIds")
    type: Optional[StrictStr] = Field(default='LocationCriterion', alias="Type")
    __properties: ClassVar[List[str]] = ["LocationId", "LocationType", "DisplayName", "EnclosedLocationIds", "Type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	
    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())
	
    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LocationCriterion from a JSON string"""
        return cls.from_dict(json.loads(json_str))
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if location_id (nullable) is None
        # and model_fields_set contains the field
        if self.location_id is None and "location_id" in self.model_fields_set:
            _dict['LocationId'] = None

        # set to None if location_type (nullable) is None
        # and model_fields_set contains the field
        if self.location_type is None and "location_type" in self.model_fields_set:
            _dict['LocationType'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['DisplayName'] = None

        # set to None if enclosed_location_ids (nullable) is None
        # and model_fields_set contains the field
        if self.enclosed_location_ids is None and "enclosed_location_ids" in self.model_fields_set:
            _dict['EnclosedLocationIds'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LocationCriterion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "LocationId": obj.get("LocationId") if obj.get("LocationId") is not None else None,
                        "LocationType": obj.get("LocationType") if obj.get("LocationType") is not None else None,
                        "DisplayName": obj.get("DisplayName") if obj.get("DisplayName") is not None else None,
                        "EnclosedLocationIds": obj.get("EnclosedLocationIds"),
                        "Type": obj.get("Type") if obj.get("Type") is not None else 'LocationCriterion'
        })
        return _obj
