# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.migration_status import MigrationStatus
from typing_extensions import Self

class MigrationStatusInfo(BaseModel):
    """
    MigrationStatusInfo
    """ # noqa: E501
    migration_type: Optional[StrictStr] = Field(default=None, alias="MigrationType")
    start_time_in_utc: Optional[datetime] = Field(default=None, alias="StartTimeInUtc")
    status: Optional[MigrationStatus] = Field(default=None, alias="Status")
    __properties: ClassVar[List[str]] = ["MigrationType", "StartTimeInUtc", "Status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if migration_type (nullable) is None
        # and model_fields_set contains the field
        if self.migration_type is None and "migration_type" in self.model_fields_set:
            _dict['MigrationType'] = None

        # set to None if start_time_in_utc (nullable) is None
        # and model_fields_set contains the field
        if self.start_time_in_utc is None and "start_time_in_utc" in self.model_fields_set:
            _dict['StartTimeInUtc'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['Status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MigrationStatusInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "MigrationType": obj.get("MigrationType") if obj.get("MigrationType") is not None else None,
                        "StartTimeInUtc": obj.get("StartTimeInUtc") if obj.get("StartTimeInUtc") is not None else None,
                        "Status": obj.get("Status") if obj.get("Status") is not None else None
        })
        return _obj
