# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.ad_recommendation_text_refine_operation import AdRecommendationTextRefineOperation
from openapi_client.models.campaign.responsive_search_ad import ResponsiveSearchAd
from typing_extensions import Self

class RefineResponsiveSearchAdRecommendationRequest(BaseModel):
    """
    RefineResponsiveSearchAdRecommendationRequest
    """ # noqa: E501
    responsive_search_ad: Optional[ResponsiveSearchAd] = Field(default=None, alias="ResponsiveSearchAd")
    text_refine_operations: Optional[List[Optional[AdRecommendationTextRefineOperation]]] = Field(default=None, alias="TextRefineOperations")
    __properties: ClassVar[List[str]] = ["ResponsiveSearchAd", "TextRefineOperations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of responsive_search_ad
        if self.responsive_search_ad:
            _dict['ResponsiveSearchAd'] = self.responsive_search_ad.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in text_refine_operations (list)
        _items = []
        if self.text_refine_operations:
            for _item_text_refine_operations in self.text_refine_operations:
                if _item_text_refine_operations:
                    _items.append(_item_text_refine_operations.to_dict())
            _dict['TextRefineOperations'] = _items
        # set to None if responsive_search_ad (nullable) is None
        # and model_fields_set contains the field
        if self.responsive_search_ad is None and "responsive_search_ad" in self.model_fields_set:
            _dict['ResponsiveSearchAd'] = None

        # set to None if text_refine_operations (nullable) is None
        # and model_fields_set contains the field
        if self.text_refine_operations is None and "text_refine_operations" in self.model_fields_set:
            _dict['TextRefineOperations'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RefineResponsiveSearchAdRecommendationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ResponsiveSearchAd": ResponsiveSearchAd.from_dict(obj["ResponsiveSearchAd"]) if obj.get("ResponsiveSearchAd") is not None else None,
                        "TextRefineOperations": [AdRecommendationTextRefineOperation.from_dict(_item) for _item in obj["TextRefineOperations"]] if obj.get("TextRefineOperations") is not None else None
        })
        return _obj
