# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class ResponsiveSearchAdsSetting(BaseModel):
    """
    ResponsiveSearchAdsSetting
    """ # noqa: E501
    auto_generated_assets_enabled: Optional[StrictBool] = Field(default=None, alias="AutoGeneratedAssetsEnabled")
    type: Optional[StrictStr] = Field(default='ResponsiveSearchAdsSetting', alias="Type")
    __properties: ClassVar[List[str]] = ["AutoGeneratedAssetsEnabled", "Type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	
    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())
	
    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponsiveSearchAdsSetting from a JSON string"""
        return cls.from_dict(json.loads(json_str))
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if auto_generated_assets_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.auto_generated_assets_enabled is None and "auto_generated_assets_enabled" in self.model_fields_set:
            _dict['AutoGeneratedAssetsEnabled'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponsiveSearchAdsSetting from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AutoGeneratedAssetsEnabled": obj.get("AutoGeneratedAssetsEnabled") if obj.get("AutoGeneratedAssetsEnabled") is not None else None,
                        "Type": obj.get("Type") if obj.get("Type") is not None else 'ResponsiveSearchAdsSetting'
        })
        return _obj
