# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from typing_extensions import Self

class ShoppingSetting(BaseModel):
    """
    ShoppingSetting
    """ # noqa: E501
    priority: Optional[StrictInt] = Field(default=None, alias="Priority")
    sales_country_code: Optional[StrictStr] = Field(default=None, alias="SalesCountryCode")
    store_id: Optional[StrictStr] = Field(default=None, alias="StoreId")
    local_inventory_ads_enabled: Optional[StrictBool] = Field(default=None, alias="LocalInventoryAdsEnabled")
    shoppable_ads_enabled: Optional[StrictBool] = Field(default=None, alias="ShoppableAdsEnabled")
    feed_label: Optional[StrictStr] = Field(default=None, alias="FeedLabel")
    type: Optional[StrictStr] = Field(default='ShoppingSetting', alias="Type")
    __properties: ClassVar[List[str]] = ["Priority", "SalesCountryCode", "StoreId", "LocalInventoryAdsEnabled", "ShoppableAdsEnabled", "FeedLabel", "Type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	
    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())
	
    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShoppingSetting from a JSON string"""
        return cls.from_dict(json.loads(json_str))
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['Priority'] = None

        # set to None if sales_country_code (nullable) is None
        # and model_fields_set contains the field
        if self.sales_country_code is None and "sales_country_code" in self.model_fields_set:
            _dict['SalesCountryCode'] = None

        # set to None if store_id (nullable) is None
        # and model_fields_set contains the field
        if self.store_id is None and "store_id" in self.model_fields_set:
            _dict['StoreId'] = None

        # set to None if local_inventory_ads_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.local_inventory_ads_enabled is None and "local_inventory_ads_enabled" in self.model_fields_set:
            _dict['LocalInventoryAdsEnabled'] = None

        # set to None if shoppable_ads_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.shoppable_ads_enabled is None and "shoppable_ads_enabled" in self.model_fields_set:
            _dict['ShoppableAdsEnabled'] = None

        # set to None if feed_label (nullable) is None
        # and model_fields_set contains the field
        if self.feed_label is None and "feed_label" in self.model_fields_set:
            _dict['FeedLabel'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShoppingSetting from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Priority": obj.get("Priority") if obj.get("Priority") is not None else None,
                        "SalesCountryCode": obj.get("SalesCountryCode") if obj.get("SalesCountryCode") is not None else None,
                        "StoreId": obj.get("StoreId") if obj.get("StoreId") is not None else None,
                        "LocalInventoryAdsEnabled": obj.get("LocalInventoryAdsEnabled") if obj.get("LocalInventoryAdsEnabled") is not None else None,
                        "ShoppableAdsEnabled": obj.get("ShoppableAdsEnabled") if obj.get("ShoppableAdsEnabled") is not None else None,
                        "FeedLabel": obj.get("FeedLabel") if obj.get("FeedLabel") is not None else None,
                        "Type": obj.get("Type") if obj.get("Type") is not None else 'ShoppingSetting'
        })
        return _obj
