# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self

class UetTagIndustry(str, Enum):
    ADULTGAMBLING = 'AdultGambling'

    AUTOS = 'Autos'

    B2BSERVICES = 'B2BServices'

    B2CSERVICES = 'B2CServices'

    CPG = 'CPG'

    CAREERSEDUCATION = 'CareersEducation'

    COMMUNITYSOCIALCHARITABLEGROUPS = 'CommunitySocialCharitableGroups'

    ENTERTAINMENT = 'Entertainment'

    FINANCIALSERVICESINSURANCE = 'FinancialServicesInsurance'

    GOVERNMENT = 'Government'

    HEALTHWELLNESS = 'HealthWellness'

    REALESTATE = 'RealEstate'

    RESTAURANTSFOOD = 'RestaurantsFood'

    RETAIL = 'Retail'

    SCIENCESOCIALSCIENCEOTHERS = 'ScienceSocialScienceOthers'

    TECHNOLOGYTELECOMMUNICATIONS = 'TechnologyTelecommunications'

    TRAVELTRANSPORTATION = 'TravelTransportation'

    OTHER = 'Other'

    UNKNOWN = 'Unknown'

	
    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UetTagIndustry from a JSON string"""
        return cls(json.loads(json_str))


