# coding: utf-8

"""
    CampaignManagementService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union, Set
from openapi_client.models.campaign.linked_in_segment import LinkedInSegment
from typing_extensions import Self

class UpdateLinkedInSegmentsRequest(BaseModel):
    """
    UpdateLinkedInSegmentsRequest
    """ # noqa: E501
    linked_in_segments: Optional[List[Optional[LinkedInSegment]]] = Field(default=None, alias="LinkedInSegments")
    __properties: ClassVar[List[str]] = ["LinkedInSegments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
	

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in linked_in_segments (list)
        _items = []
        if self.linked_in_segments:
            for _item_linked_in_segments in self.linked_in_segments:
                if _item_linked_in_segments:
                    _items.append(_item_linked_in_segments.to_dict())
            _dict['LinkedInSegments'] = _items
        # set to None if linked_in_segments (nullable) is None
        # and model_fields_set contains the field
        if self.linked_in_segments is None and "linked_in_segments" in self.model_fields_set:
            _dict['LinkedInSegments'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateLinkedInSegmentsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "LinkedInSegments": [LinkedInSegment.from_dict(_item) for _item in obj["LinkedInSegments"]] if obj.get("LinkedInSegments") is not None else None
        })
        return _obj
